version: '3.7'
services:
  web:         
    build: 
      context: .
    command: sh -c "python -m flask run --host=0.0.0.0"
    container_name: mywebsite
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app 
    